- hosts: virtualmachines
  become: true
  gather_facts: True
  vars_files:
    - vars/default.yml
  roles:
    - mysql

- hosts: virtualmachines
  become: true
  gather_facts: True
  vars_files:
    - vars/default.yml
  roles:
    - nginx
    - php
    - wordpress



# Specific modules only       MySQL, PHP, Nginx, Wordpress
# System installation         System
